name: Publish Stable Release

on:
  workflow_dispatch:
  push:
    branches: [master, main]

permissions:
  contents: write   # required for version bump commit and release tag

jobs:
  publish_stable:
    if: github.actor != 'github-actions[bot]'
    uses: OpenVoiceOS/gh-automations/.github/workflows/publish-stable.yml@e37a97650feada694abb6420a84bbd23a71d6bb1
    secrets:
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
      MATRIX_TOKEN: ${{ secrets.MATRIX_TOKEN }}
    with:
      version_file: 'pyeye/version.py'
      publish_pypi: true
      publish_release: true
      sync_dev: true
      notify_matrix: true
